/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/Homeview/AppBar.vue')['default']
    Drawer: typeof import('./src/components/Homeview/Drawer.vue')['default']
    Main: typeof import('./src/components/Homeview/Main.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SnackBar: typeof import('./src/components/SnackBar.vue')['default']
  }
}
